services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: risk_db
      POSTGRES_PASSWORD: secret_password
      POSTGRES_USER: bank_admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
